"""Add items table

Revision ID: 292582470f94
Revises: e01b7b990e0d
Create Date: 2024-03-09 18:33:01.618515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292582470f94'
down_revision = 'e01b7b990e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_items_user_id_users')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_items_shop_id_shops')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
